version: '3'
services:
  production:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    stdin_open: true
    tty: true

  proxy:
    build:
      context: ./ProxyServer
      dockerfile: Dockerfile.proxy
    ports:
      - "4000:4000"
    stdin_open: true
    tty: true