Drop table if exists politicians;
create table politicians (
    id int NOT NULL auto_increment,
	FirstName varchar(255) NOT NULL,
    LastName varchar(255) NOT NULL,
    Age int,
    Current_Position varchar(255) default NULL,
    Running_Position varchar(255) NOT NULL,
    State varchar(255),
    Incumbent bool NOT NULL,
    Party varchar(255),
    PRIMARY KEY (id) 
);

Insert into politicians (FirstName, LastName, Age, Current_Position, Running_Position, State, Incumbent, Party)
Values ("Donald" ,"Trump", 74, "President", "President", Null, true, "Republican"), 
("Joe", "Biden", 77, "N/A", "President", Null, false, "Democrat"),
("Roy", "Cooper", 63, "Governor", "Governor", "North Carolina", true, "Democrat"),
("Dan", "Forest", 53, "Lieutenant Governor", "Governor", "North Carolina",false, "Republican"),
("Steven", "Difiore",35, "N/A", "Governor", "North Carolina",false, "Libertarian"),
("Al", "Pisano", 57, "N/A", "Governor", "North Carolina",false, "Consitution"),
("Thom", "Tillis", 60, "Senator", "Senator", "North Carolina",true, "Republican"),
("Cal", "Cunningham", 47, "N/A", "Senator", "North Carolina",false, "Democrat"),
("G.K", "Butterfield", 73, "Representative", "House of Representatives: District 1", "North Carolina",true, "Democrat"),
("Sandy", "Smith", 37, "N/A", "House of Representatives: District 1", "North Carolina",false, "Republican"),
("Deborah", "Ross", 57, "N/A", "House of Representatives: District 2", "North Carolina",false, "Democrat"),
("Alan", "Swain", 66, "N/A", "House of Representatives: District 2", "North Carolina",false, "Republican"),
("Jeff", "Matemu", 45, "N/A", "House of Representatives: District 2", "North Carolina",false, "Libertarian"),
("Greg", "Murphy", 57, "House of Representatives: District 3", "House of Representatives: District 3", "North Carolina",true, "Republican"),
("Daryl", "Farrow", 59, "N/A", "House of Representatives: District 3", "North Carolina",FALSE, "Democrat"),
("David", "Price", 80, "House of Representatives: District 4", "House of Representatives: District 4", "North Carolina",true, "Democrat"),
("Robert", "Thomas", 68, "N/A", "House of Representatives: District 4", "North Carolina",FALSE, "Republican"),
("Virginia", "Fox", 77, "House of Representatives: District 5", "House of Representatives: District 5", "North Carolina",true, "Republican"),
("David", "Brown", 46, "N/A", "House of Representatives: District 5", "North Carolina",FALSE, "Democrat"),
("Jeff", "Gregory", 62, "N/A", "House of Representatives: District 5", "North Carolina",FALSE, "Constition"),
("Joseph Lee", "Haywood", NULL, "N/A", "House of Representatives: District 6", "North Carolina",FALSE, "Republican"),
("Kathy", "Manning", NULL, "N/A", "House of Representatives: District 6", "North Carolina",FALSE, "Democrat"),
("Christopher","Ward",NULL,"N/A","House of Representtives: District 7","North Carolina",false,"Democrat"),
("David","Rouzer",48,"House of Representtives: District 7","House of Representtives: District 7","North Carolina",true,"Republican"),
("Theresa","Everett",50,"N/A","House of Representtives: District 7","North Carolina",false,"Independent"),
("Patricia","Timmons-Goodson",60,"Associate Justice of NC Supreme Court","House of Representtives: District 8","North Carolina",false,"Democrat"),
("Richard","Hudson",48,"House of Representtives: District 8","House of Representtives: District 8","North Carolina",true,"Republican"),
("Cynthia","Wallace",NULL,"N/A","House of Representtives: District 9","North Carolina",false,"Democrat"),
("Dan","Bishop",56,"House of Representtives: District 9","House of Representtives: District 9","North Carolina",true,"Republican"),
("David","Parker",NULL,"N/A","House of Representtives: District 10","North Carolina",false,"Democrat"),
("Patrick","McHenry",45,"House of Representtives: District 10","House of Representtives: District 10","North Carolina",true,"Republican"),
("Moe","Davis",62,"N/A","House of Representtives: District 11","North Carolina",false,"Democrat"),
("Maddison","Cawthorn",26,"N/A","House of Representtives: District 11","North Carolina",false,"Republican"),
("Tracy","DeBruhl",NULL,"N/A","House of Representtives: District 11","North Carolina",false,"Libertarian"),
("Tamara","winak",NULL,"N/A","House of Representtives: District 11","North Carolina",false,"Green"),
("Alma","Adams",74,"House of Representtives: District 12","House of Representtives: District 12","North Carolina",true,"Democrat"),
("Scott","Huffman",NULL,"N/A","House of Representtives: District 13","North Carolina",false,"Democrat"),
("Ted","Budd",49,"House of Representtives: District 12","House of Representtives: District 13","North Carolina",true,"Republican")
;